### ISSUE TITLE
import type error in deno v1.4

### ISSUE THREAD

**Issue by buttercubz** [littletof/prettyBenching#23]
![image](https://user-images.githubusercontent.com/47539192/93103432-9dac9e00-f67a-11ea-91fc-718c8d9199de.png)

in deno 1.4 the types must be imported using:
 ```ts
import type {....} from "... /"
```
since that accuses an error

**Comment by littletof** [comment]
@buttercubz Thanks for the report,  will get to it later today to fix it.

**Comment by littletof** [comment]
@buttercubz this should be fixed in `v0.2.4`.

Please give feedback when you have time, if I fixed this error properly.

**Comment by buttercubz** [comment]
@littletof thanks a lot for the quick solution, works fine again
