### ISSUE TITLE
suggestion: add json output to pretty Benchmark

### ISSUE THREAD

**Issue by buttercubz** [littletof/prettyBenching#26]
It is possible to add a prettyBenchmarkJson function since it seems that it would be a very useful function

**Comment by littletof** [comment]
@buttercubz I'm not sure what functionality you suggest, but I'm working on something that may do what you suggest, it should be out this week.
([sneak peek 🤐](https://github.com/littletof/prettyBenching/tree/feature/historic#prettybenchmarkhistory))

If its an other functionality, please elaborate

**Comment by littletof** [comment]
@buttercubz closing it as stale, but feel free to reopen it, if you want to discuss it, im interested in new features.
