### ISSUE TITLE
Update to 0.1.0 changes requirements of options

### ISSUE THREAD

**Issue by khrome83** [littletof/prettyBenching#5]
<img width="674" alt="Screen Shot 2020-06-18 at 7 02 52 AM" src="https://user-images.githubusercontent.com/1844739/85017840-c5e73800-b131-11ea-9b8c-2032757f2b70.png">

Once upgrading from 0.0.3 to 0.1.0, the options object became required, even if it's just a {}. 

Should this be optional? Or should the docs be updated to show it always having at least an optional empty object passed in?

I can open a PR if I get some direction on what is expected.

**Comment by littletof** [comment]
It should be optional, I think I missed it while refactoring. I will look into it now, as repo is not too contributor friendly, but once its done (or you feel brave :) ), PR-s are very welcome.

**Comment by khrome83** [comment]
@littletof - I was just opening an MR. But I didn't do the no-color default or the test. So yours is good. I reviewed it. 

Also, your code is clean enough to contribute. Can I suggest you use `deno fmt` though? Most people will be running the VS Code deno plugin with runs it automatically. For me to contribute I would have had to turn off the auto-formatting.

Thank you for the quick fix though!

**Comment by littletof** [comment]
@khrome83 Thanks for the review! I added a small description hopefully clearing up a bit, how graphs work. Is it clear with it how the graphs works now?

What files does fmt not like? I use `fmt` and `lint` too. Were there any changes in them? Sometimes it just adds them in changed for me, but when you stage it disappers as nothing changed.

Do you see any other issues right now? If not, then I will release the fix as 0.1.1

**Comment by khrome83** [comment]
It was mostly where it wrapped the line. I wonder if something else is formatting for you on staging? Like a githook that has a differnt formatter. I know Prettier and Deno Fmt are not making the same decisions. 

Closing this.

**Comment by littletof** [comment]
No, I `deno fmt`, `deno lint --unstable`, then commit. I dont use any hooks. I'm on windows, dont know, if it differs, but is shouldnt.
